# Dependencies
markdown:         kramdown 
highlighter:      rouge 

# Permalinks
permalink:        pretty

# Setup
title:            Mia Gil Epner 
tagline:          ''
description:      'Software engineer and (soon-to-be) Berkeley alum.'
url:              https://miagilepner.com/
baseurl:          /
site:             https://miagilepner.com/
author:
  name:           'Mia Gil Epner'


# Custom vars
version:          2.1.0


# Gems
gems:             [jekyll-paginate, jekyll-gist, redcarpet]
paginate:         5
paginate_path:    "blog/page:num"
